title: EE learning
author: Zihao Yu
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Here is the first step of an EE student transfering to IT studnet.
theme: minima
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
